import type { Metadata } from 'next'
import { DM_Mono, Exo_2 } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const exo2 = Exo_2({
  variable: '--font-exo-2',
  subsets: ['latin'],
})

const dmMono = DM_Mono({
  variable: '--font-dm-mono',
  subsets: ['latin'],
  weight: ['300', '500'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${exo2.variable} ${dmMono.variable} antialiased`}>
          {children}
        </body>
      </html>
    </Providers>
  )
}
